### ISSUE TITLE
2D scatter issue with matplotlib 3.3.0

### ISSUE THREAD

**Issue by specmicp** [glue-viz/glue#2169]
I cannot add data to a 2D scatter issue with matplotlib 3.3.x, because of the following error:

```
Traceback (most recent call last):
  File "...dev/environments/glue/glue/utils/qt/decorators.py", line 61, in decorated
    return f(*args, **kwargs)
  File "...dev/environments/glue/glue/viewers/common/qt/data_viewer.py", line 217, in add_data
    return super(DataViewer, self).add_data(data)
  File "...dev/environments/glue/glue/viewers/common/viewer.py", line 207, in add_data
    layer = get_layer_artist_from_registry(data, self) or self.get_data_layer_artist(data)
  File "...dev/environments/glue/glue/utils/matplotlib.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "...dev/environments/glue/glue/utils/matplotlib.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "...dev/environments/glue/glue/viewers/common/viewer.py", line 232, in get_data_layer_artist
    return self.get_layer_artist(self._data_artist_cls, layer=layer, layer_state=layer_state)
  File "...dev/environments/glue/glue/utils/matplotlib.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "...dev/environments/glue/glue/utils/matplotlib.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "...dev/environments/glue/glue/viewers/matplotlib/viewer.py", line 298, in get_layer_artist
    return cls(self.axes, self.state, layer=layer, layer_state=layer_state)
  File "...dev/environments/glue/glue/viewers/scatter/layer_artist.py", line 163, in __init__
    label=None)
  File "...dev/environments/glue_dev/lib/python3.7/site-packages/mpl_scatter_density/generic_density_artist.py", line 56, in __init__
    super(GenericDensityArtist, self).__init__(ax, array_func=histogram2d_func, dpi=dpi, update_while_panning=update_while_panning, **kwargs)
  File "...dev/environments/glue_dev/lib/python3.7/site-packages/mpl_scatter_density/base_image_artist.py", line 56, in __init__
    super(BaseImageArtist, self).__init__(ax, **kwargs)
  File "...dev/environments/glue_dev/lib/python3.7/site-packages/matplotlib/image.py", line 905, in __init__
    **kwargs
  File "...dev/environments/glue_dev/lib/python3.7/site-packages/matplotlib/image.py", line 243, in __init__
    cm.ScalarMappable.__init__(self, norm, cmap)
  File "...dev/environments/glue_dev/lib/python3.7/site-packages/matplotlib/cm.py", line 234, in __init__
    self.set_norm(norm)  # The Normalize instance of this ScalarMappable.
  File "...dev/environments/glue_dev/lib/python3.7/site-packages/mpl_scatter_density/generic_density_artist.py", line 91, in set_norm
    if norm.vmin is not None:
AttributeError: 'NoneType' object has no attribute 'vmin'
```

Everything works correctly with matplotlib 3.2.2

**Comment by astrofrog** [comment]
Can you try updating mpl-scatter-density to the latest version?

**Comment by specmicp** [comment]
Yes that does the trick ! Sorry I should have figured this one by myself.

**Comment by astrofrog** [comment]
No it wasn't obvious! :)
